# Generated by Django 4.1.5 on 2023-01-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(max_length=20)),
                ('version', models.IntegerField(null=True)),
                ('coins', models.IntegerField()),
            ],
        ),
    ]
