# Generated by Django 4.1.5 on 2023-01-31 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_id_alter_wallet_transactionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='transactionId',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='version',
        ),
    ]
