# Generated by Django 4.1.5 on 2023-01-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_wallet_transactionid_remove_wallet_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.IntegerField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
