# Generated by Django 4.1.5 on 2023-01-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
